version: "3.1"

services:
  frontend:
    image: node:latest
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    depends_on:
      - backend

  backend:
    image: backend
    build: ./backend
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www/
      - ./backend/public/:/var/www/html/
    command: sh -c "composer install && apache2-foreground"
    ports:
      - 8200:80
    depends_on:
      - db

  db:
    image: postgres
    env_file: .env
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432