version: "3.1"

services:
  frontend:
    image: node
    working_dir: /app
    command: "npm start"
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: backend
    build: ./backend
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www/
      - ./backend/public/:/var/www/html/
    ports:
      - 8200:80
    depends_on:
      - db

  db:
    image: postgres
    env_file: .env
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    ports:
      - 5433:5432