DO $$
BEGIN
    -- Check if all tables exist
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'usuarios'
    ) AND EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'cartas'
    ) AND EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'coleccion'
    ) AND EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'mercado'
    ) THEN
        -- If all tables exist, do nothing
        RAISE NOTICE 'Las tablas ya existen';
    ELSEIF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name IN ('usuarios', 'cartas', 'coleccion', 'mercado')
    ) THEN
        -- If some tables exist but not all, there might be an issue
        RAISE NOTICE 'Algunas de las tablas ya existen, puede que la base de datos este corrupta, o estes usando una versión antigua de este script';
    ELSE
        -- If none of the tables exist, create them and add example data
        CREATE TABLE usuarios (
            id SERIAL PRIMARY KEY,
            username VARCHAR(255),
            email VARCHAR(255),
            name VARCHAR(255),
            password VARCHAR(70),
            saldo INTEGER DEFAULT 500,
            img_url VARCHAR(255),
            sobres INTEGER DEFAULT 5,
            is_admin BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE cartas (
            id SERIAL PRIMARY KEY,
            nombre VARCHAR(255),
            position VARCHAR(255) CHECK (position IN ('pg', 'sg', 'sf', 'pf', 'c')),
            rarity VARCHAR(255) CHECK (rarity IN ('comun', 'rara', 'heroe')),
            puntuacion SMALLINT,
            img_url VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE coleccion (
            id SERIAL PRIMARY KEY,
            id_usuario INTEGER REFERENCES usuarios(id),
            id_carta INTEGER REFERENCES cartas(id),
            cantidad INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE mercado (
            id SERIAL PRIMARY KEY,
            id_coleccion INT REFERENCES coleccion(id),
            precio INTEGER,
            vendida BOOLEAN DEFAULT FALSE,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

        -- Add example data
        INSERT INTO usuarios (username, email, name, password, saldo, img_url, sobres, is_admin) VALUES
            ('fran', 'fran@email.es', 'FcoJavier9', '8ec98ed17b2fba4b6065111ab34427993f210e878414df557b31b443aacaa327', 100, 'url1/usuarios/1.jpg',5,true),
            ('pablo', 'pablo@email.es', 'PabloNarVal', 'passwordhash2', 150, 'img/usuarios/2.jpg',5,false),
            ('rafa', 'rafa@email.es', 'Rafa el guay', 'passwordhash3', 420, 'img/usuarios/3.jpg',5,false),
            ('marc', 'marc@email.com', 'Marc spector', 'passwordhash4', 200, 'img/usuarios/4.jpg',5,false),
            ('steven', 'steven@email.com', 'Steven Grant', 'passwordhash5', 250, 'img/usuarios/5.jpg',5,false),
            ('mario', 'mario@email.com', 'Mario Mario', 'passwordhash6', 300, 'img/usuarios/6.jpg',5,false),
            ('maurice', 'sonic@email.com', 'S. Maurice Hedgehog', 'passwordhash7', 350, 'img/usuarios/7.jpg',5,false),
            ('Alec', 'wizard@email.com', 'Alec Azzam', 'passwordhash8', 400, 'img/usuarios/8.jpg',5,false),
            ('bruce', 'bruce@email.com', 'Bruce Wayne', 'passwordhash9', 450, 'img/usuarios/9.jpg',5,false),
            ('clark', 'clark@email.com', 'Clark Kent', 'passwordhash10', 500, 'img/usuarios/10.jpg',5,false),
            ('peter', 'peter@email.com', 'Peter Parker', 'passwordhash11', 550, 'img/usuarios/11.jpg',5,false),
            ('logan', 'logan@email.com', 'Logan Howlett', 'passwordhash12', 600, 'img/usuarios/12.jpg',5,false),
            ('natasha', 'natasha@email.com', 'Natasha Romanoff', 'passwordhash13', 650, 'img/usuarios/13.jpg',5,false),
            ('steve', 'steve@email.com', 'Steve Rogers', 'passwordhash14', 700, 'img/usuarios/14.jpg',5,false),
            ('diana', 'diana@email.com', 'Diana Prince', 'passwordhash15', 750, 'img/usuarios/15.jpg',5,false),
            ('barry', 'barry@email.com', 'Barry Allen', 'passwordhash16', 800, 'img/usuarios/16.jpg',5,false),
            ('arthur', 'arthur@email.com', 'Arthur Curry', 'passwordhash17', 850, 'img/usuarios/17.jpg',5,false),
            ('hal', 'hal@email.com', 'Hal Jordan', 'passwordhash18', 900, 'img/usuarios/18.jpg',5,false),
            ('oliver', 'oliver@email.com', 'Oliver Queen', 'passwordhash19', 950, 'img/usuarios/19.jpg',5,false),
            ('jake', 'jake@email.com', 'Jake Lockley', 'passwordhash20', 1000, 'img/usuarios/20.jpg',5,false);

        INSERT INTO cartas (nombre, position, rarity, puntuacion, img_url) VALUES
            ('Darius Garland', 'pg', 'comun', 62, 'assets/cartas/1.jpg'),
            ('LaMelo Ball', 'pg', 'comun', 63, 'assets/cartas/2.jpg'),
            ('Kristaps Porzingis', 'pf', 'comun', 64, 'assets/cartas/3.jpg'),
            ('Jrue Holiday', 'pg', 'comun', 65, 'assets/cartas/4.jpg'),
            ('Khris Middleton', 'sf', 'comun', 66, 'assets/cartas/5.jpg'),
            ('CJ McCollum', 'sg', 'comun', 67, 'assets/cartas/6.jpg'),
            ('DeMar DeRozan', 'sf', 'comun', 68, 'assets/cartas/7.jpg'),
            ('Kyrie Irving', 'pg', 'comun', 69, 'assets/cartas/8.jpg'),
            ('Domantas Sabonis', 'pf', 'comun', 70, 'assets/cartas/9.jpg'),
            ('Julius Randle', 'pf', 'comun', 71, 'assets/cartas/10.jpg'),
            ('Brandon Ingram', 'sf', 'comun', 72, 'assets/cartas/11.jpg'),
            ('Bradley Beal', 'sg', 'comun', 73, 'assets/cartas/12.jpg'),
            ('Trae Young', 'pg', 'comun', 74, 'assets/cartas/13.jpg'),
            ('Karl-Anthony Towns', 'c', 'comun', 75, 'assets/cartas/14.jpg'),
            ('Zion Williamson', 'pf', 'comun', 76, 'assets/cartas/15.jpg'),
            ('Paul George', 'sf', 'comun', 77, 'assets/cartas/16.jpg'),
            ('Bam Adebayo', 'c', 'comun', 78, 'assets/cartas/17.jpg'),
            ('Jaylen Brown', 'sg', 'comun', 79, 'assets/cartas/18.jpg'),
            ('Pascal Siakam', 'pf', 'comun', 80, 'assets/cartas/19.jpg'),
            ('De''Aaron Fox', 'pg', 'comun', 81, 'assets/cartas/20.jpg'),
            ('Jalen Brunson', 'pg', 'comun', 82, 'assets/cartas/21.jpg'),
            ('Shai Gilgeous-Alexander', 'sg', 'comun', 83, 'assets/cartas/22.jpg'),
            ('Donovan Mitchell', 'sg', 'comun', 84, 'assets/cartas/23.jpg'),
            ('Devin Booker', 'sg', 'comun', 85, 'assets/cartas/24.jpg'),
            ('Damian Lillard', 'pg', 'rara', 86, 'assets/cartas/25.jpg'),
            ('Jimmy Butler', 'sf', 'rara', 87, 'assets/cartas/26.jpg'),
            ('Anthony Davis', 'pf', 'rara', 88, 'assets/cartas/27.jpg'),
            ('Ja Morant', 'pg', 'rara', 89, 'assets/cartas/28.jpg'),
            ('LeBron James', 'sf', 'rara', 90, 'assets/cartas/29.jpg'),
            ('Kevin Durant', 'sf', 'rara', 91, 'assets/cartas/30.jpg'),
            ('Stephen Curry', 'pg', 'rara', 92, 'assets/cartas/31.jpg'),
            ('Jayson Tatum', 'sf', 'rara', 93, 'assets/cartas/32.jpg'),
            ('Joel Embiid', 'c', 'rara', 94, 'assets/cartas/33.jpg'),
            ('Luka Doncic', 'pg', 'rara', 96, 'assets/cartas/34.jpg'),
            ('Giannis Antetokounmpo', 'pf', 'rara', 97, 'assets/cartas/35.jpg'),
            ('Nikola Jokic', 'c', 'rara', 97, 'assets/cartas/36.jpg'),
            ('Julius Erving', 'sf', 'heroe', 90, 'assets/cartas/37.jpg'),
            ('Oscar Robertson', 'pg', 'heroe', 91, 'assets/cartas/38.jpg'),
            ('Bill Russell', 'c', 'heroe', 92, 'assets/cartas/39.jpg'),
            ('Wilt Chamberlain', 'c', 'heroe', 93, 'assets/cartas/40.jpg'),
            ('Hakeem Olajuwon', 'c', 'heroe', 94, 'assets/cartas/41.jpg'),
            ('Kobe Bryant', 'sg', 'heroe', 95, 'assets/cartas/42.jpg'),
            ('Tim Duncan', 'pf', 'heroe', 95, 'assets/cartas/43.jpg'),
            ('Shaquille O''Neal', 'c', 'heroe', 96, 'assets/cartas/44.jpg'),
            ('Larry Bird', 'sf', 'heroe', 97, 'assets/cartas/45.jpg'),
            ('Magic Johnson', 'pg', 'heroe', 98, 'assets/cartas/46.jpg'),
            ('Kareem Abdul-Jabbar', 'c', 'heroe', 99, 'assets/cartas/47.jpg'),
            ('Michael Jordan', 'sg', 'heroe', 100, 'assets/cartas/48.jpg');

        INSERT INTO coleccion (id_usuario, id_carta, cantidad) VALUES
            (9, 48, 5),
            (9, 47, 2),
            (18, 46, 7),
            (5, 45, 2),
            (13, 43, 6),
            (16, 41, 5),
            (1, 40, 5),
            (18, 38, 10),
            (3, 37, 3),
            (7, 36, 2),
            (6, 35, 2),
            (13, 34, 9),
            (15, 33, 1),
            (13, 32, 6),
            (4, 31, 2),
            (12, 30, 6),
            (8, 29, 4),
            (4, 28, 2),
            (20, 27, 10),
            (1, 26, 6),
            (3, 25, 4),
            (19, 24, 5),
            (3, 23, 6),
            (10, 22, 6),
            (8, 21, 6),
            (10, 20, 1),
            (18, 19, 3),
            (6, 18, 7),
            (12, 17, 10),
            (20, 16, 4),
            (3, 15, 5),
            (20, 14, 8),
            (15, 13, 2),
            (12, 12, 9),
            (3, 11, 6),
            (9, 10, 5),
            (12, 9, 4),
            (15, 8, 1),
            (4, 7, 3),
            (20, 6, 7),
            (13, 5, 9),
            (15, 4, 7),
            (20, 3, 10),
            (4, 2, 4),
            (18, 1, 1),
            (20, 48, 8),
            (17, 47, 2),
            (13, 46, 6),
            (17, 45, 2),
            (13, 44, 9),
            (2, 43, 10),
            (20, 42, 7),
            (19, 41, 1),
            (20, 40, 3),
            (14, 39, 9),
            (18, 38, 10),
            (18, 37, 9),
            (10, 36, 10),
            (19, 35, 7),
            (5, 34, 7),
            (20, 33, 5),
            (10, 32, 1),
            (9, 31, 7),
            (12, 30, 5),
            (19, 29, 7),
            (7, 28, 7),
            (1, 27, 6),
            (11, 26, 2),
            (15, 25, 10),
            (5, 24, 6),
            (2, 23, 1),
            (20, 22, 2),
            (18, 21, 9),
            (17, 20, 7),
            (8, 19, 10),
            (15, 18, 1),
            (13, 17, 6),
            (14, 16, 4),
            (14, 15, 4),
            (12, 14, 5),
            (11, 13, 3),
            (3, 12, 4),
            (11, 11, 8),
            (18, 10, 3),
            (19, 9, 4),
            (4, 8, 2),
            (4, 7, 10),
            (19, 6, 5),
            (10, 5, 6),
            (9, 4, 4),
            (12, 3, 2),
            (8, 2, 1),
            (3, 1, 9),
            (9, 37, 5),
            (9, 36, 2),
            (18, 35, 7),
            (5, 34, 2),
            (13, 33, 6),
            (16, 32, 5),
            (1, 31, 5),
            (18, 30, 10),
            (3, 29, 3),
            (7, 28, 2),
            (6, 27, 2),
            (13, 26, 9),
            (15, 25, 1),
            (13, 24, 6),
            (4, 23, 2),
            (12, 22, 6),
            (8, 21, 4),
            (4, 20, 2),
            (20, 19, 10),
            (1, 18, 6);

        INSERT INTO mercado (id_coleccion, precio, vendida) VALUES
            (55, 78, True),
            (61, 63, False),
            (46, 24, False),
            (47, 47, True),
            (65, 68, True),
            (66, 16, False),
            (21, 41, True),
            (54, 84, True),
            (8, 33, False),
            (63, 15, False),
            (25, 69, False),
            (25, 13, False),
            (93, 43, True),
            (57, 11, True),
            (3, 59, True),
            (78, 88, True),
            (54, 96, True),
            (77, 23, False),
            (22, 53, False),
            (33, 53, False),
            (97, 58, True),
            (48, 44, True),
            (45, 10, True),
            (54, 29, False),
            (33, 62, True),
            (14, 19, True),
            (42, 35, True),
            (99, 13, True),
            (11, 98, False),
            (33, 98, True),
            (63, 13, False),
            (27, 14, True),
            (20, 29, True),
            (100, 87, False),
            (58, 68, False),
            (29, 17, True),
            (83, 45, True),
            (61, 39, True),
            (83, 99, False),
            (15, 39, True),
            (26, 39, True),
            (43, 91, True),
            (33, 16, True),
            (90, 81, True),
            (100, 67, False),
            (88, 14, True),
            (60, 14, True),
            (50, 40, True),
            (73, 14, True),
            (80, 12, True),
            (53, 64, True),
            (85, 12, True),
            (9, 87, True),
            (55, 35, True),
            (11, 89, True),
            (15, 26, False),
            (57, 55, True),
            (9, 11, True),
            (60, 58, True),
            (52, 98, False),
            (28, 82, True),
            (5, 11, True),
            (31, 48, False),
            (7, 70, True),
            (55, 20, True),
            (15, 39, True),
            (17, 10, True),
            (1, 98, False),
            (7, 97, False),
            (32, 11, True),
            (70, 26, True),
            (72, 83, True),
            (86, 22, True),
            (65, 98, True),
            (37, 18, True),
            (53, 76, True),
            (17, 56, False),
            (9, 41, True),
            (49, 79, True),
            (31, 94, True),
            (100, 71, True),
            (43, 83, True),
            (67, 42, True),
            (4, 67, False),
            (86, 21, True),
            (21, 57, True),
            (13, 71, True),
            (37, 60, True),
            (28, 12, True),
            (56, 54, False),
            (1, 90, True),
            (85, 51, True),
            (23, 38, True),
            (92, 100, True),
            (61, 56, True),
            (12, 98, False),
            (9, 90, False),
            (83, 54, True),
            (41, 37, False),
            (71, 54, True);

        RAISE NOTICE 'Tablas creadas exitosamente';
    END IF;
END $$;